### ISSUE TITLE
Failed to create link no such file or directory

### ISSUE THREAD

**Issue by 13hannes11** [owtaylor/toolbox-vscode#15]
I tried the installation as follows.

1. Install vscode as flatpak
2. run through the install steps:
    1. `git clone https://github.com/owtaylor/toolbox-vscode.git`
    2. `cd toolbox-vscode`
    3. `ln -s "$PWD/code.sh" ~/.local/bin/code`

The last step produces the error message in the title because the directory `~/.local/bin` does not exist.

Therefore adding a step for creating that folder if it doesn't exist sounds like a good idea.

**Comment by owtaylor** [comment]
Added a line to the installation instructions. Thanks for the suggestion!
