### ISSUE TITLE
Unterminated quoted string bug

### ISSUE THREAD

**Issue by spikhoff** [owtaylor/toolbox-vscode#21]
After rebasing F35 to F36 I'm no longer able to open vscode in toolbox.

Steps to reproduce:

```
$ podman --version
podman version 4.0.0-rc4

$ toolbox enter
$ code .
ERRO[0000] Printing inspect output: template: all inspect:1: unterminated quoted string 
$HOME in container config is: '' - don't know how to handle this
```

**Comment by owtaylor** [comment]
This looks like some sort of incompatibility with newer podman or just a podman bug. If you find a container with 'podman ps' and try:

``` sh
podman inspect CONTAINER_NAME -format='{{ range .Config.Env }}{{ . }}{{"\n"}}{{ end }}'
```

does that produce the same error?

**Comment by spikhoff** [comment]
It does:
```
$ podman inspect fedora-toolbox-36 -format='{{ range .Config.Env }}{{ . }}{{"\n"}}{{ end }}'
ERRO[0000] Printing inspect output: template: all inspect:1: unterminated quoted string
```

**Comment by owtaylor** [comment]
Would you mind filing a bug against containers/libpod about this? It's possible that the template there is invalid in some way, but:

 * It works with older versions of podman
 * It doesn't obviously contain an unterminated quoted string

**Comment by owtaylor** [comment]
Worked around by #23
